### ISSUE TITLE
external *.tar.bz2 not at defined URL

### ISSUE THREAD

**Issue by dehann** [spillai/pybot#3]
Hi Sudeep,

Are these [links still valid](https://github.com/spillai/pybot/blob/master/externals_links.txt)?
```
./install_externals.sh
```
is having trouble finding (and so am I) the external binaries.

Thanks!

**Comment by dehann** [comment]
found this:
https://anaconda.org/s_pillai/repo

**Comment by spillai** [comment]
From now on, you can do `conda install -c s_pillai pybot` to get the latest travis-ci build.
